services:
  - type: web
    name: dyrdomdej_simple_server
    env: node

    plan: starter
    region: frankfurt
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: dyrdomdej_simple_server-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 16.18
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dyrdomdej_simple_server
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: dyrdomdej_simple_server
    plan: starter
